
// Generated by https://quicktype.io

export interface Movie {
    data: {
        Title: string;
        Year: string;
        Rated: string;
        Released: string;
        Runtime: string;
        Genre: string;
        Director: string;
        Writer: string;
        Actors: string;
        Plot: string;
        Language: string;
        Country: string;
        Awards: string;
        Poster: string;
        Ratings: Rating[];
        Metascore: string;
        imdbRating: string;
        imdbVotes: string;
        imdbID: string;
        Type: string;
        DVD: string;
        BoxOffice: string;
        Production: string;
        Website: string;
        Response: string;
    }
}

export interface Rating {
    Source: string;
    Value: string;
}


// Generated by https://quicktype.io

export interface MovieSearch {
    data: {
        Search: [
            {
                Title: string;
                Year: string;
                imdbID: string;
                Type: Type;
                Poster: string;
            }
        ],
        totalResults: string;
        Response: string;
        Error?: string
    }
}

export interface movieResult {
    title: string,
    rating: string,
    img: string,
    description: string
}
export enum Type {
    Movie = "movie",
    Series = "series",
}
